### ISSUE TITLE
macOS Support?

### ISSUE THREAD

**Issue by a7medev** [Megadardery/machine-language#2]
Hey @ahmed-dardery! I was wondering if there's a macOS build or if I can help build one using the current source code, is the current app cross-platform and ready to be built on a macOS machine or is it a Windows-only app?

**Comment by ahmed-dardery** [comment]
This is built with windows in mind as a forms application, but I believe it might  be possible to port it as a mono project.

https://www.mono-project.com/docs/about-mono/

Alternatively, let others know about this issue, if demand shows up we can work on a website alternative so it is cross platform

**Comment by a7medev** [comment]
I've created an MVP web app available [here](https://machinelanguage.vercel.app/). Thanks for the inspiration and for this great tool!
